<?php

declare(strict_types=1);

?>
<main>
	<?php get_template_part( 'template-parts/sections/about-hero' ); ?>
	<section class="about-stats" aria-labelledby="about-stats-title"><div class="container"><h1 id="about-stats-title">Навчайтеся в найбільшій школі в Україні</h1><ul class="about-stats__list"><li><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/banner-bar/icon-calendar-check.svg' ); ?>" alt="">З 2018 року на ринку</li><li><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/banner-bar/icon-document-certificate.svg' ); ?>" alt="">Освітня ліцензія</li><li><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/banner-bar/icon-rating-star.svg' ); ?>" alt="">4.9 рейтинг від клієнтів</li><li><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/banner-bar/icon-outline_school.svg' ); ?>" alt="">178 шкіл в Україні</li><li><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/banner-bar/icon-map-location.svg' ); ?>" alt="">130 міст по Україні</li><li><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/banner-bar/icon-tabler-school.svg' ); ?>" alt="">100тис+ успішних випускників</li></ul></div></section>
	<section class="about-directions" aria-label="Напрями навчання"><div class="container"><ul><li><a href="<?php echo esc_url( home_url( '/it-courses/' ) ); ?>" aria-label="Переглянути курси програмування"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/about/direction-programming.png' ); ?>" alt="Курси програмування"></a></li><li><a href="<?php echo esc_url( home_url( '/english-courses/' ) ); ?>" aria-label="Переглянути курси англійської"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/about/direction-english.png' ); ?>" alt="Курси англійської мови"></a></li><li><a href="<?php echo esc_url( home_url( '/camps/' ) ); ?>" aria-label="Переглянути табори"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/about/direction-camps.png' ); ?>" alt="Табори Logika"></a></li></ul></div></section>
	<section class="about-outcomes" aria-labelledby="about-outcomes-title"><div class="container"><h2 id="about-outcomes-title">Що отримає ваша дитина,<br>навчаючись у школі «Logika»</h2><ul><li><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/about/outcome-thinking.png' ); ?>" alt="Дитина полюбить точні науки та побачить, як шкільні предмети працюють у житті"></li><li><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/about/outcome-technology.png' ); ?>" alt="Дитина навчиться сучасним IT-технологіям, які використовують фахівці в реальних компаніях"></li><li><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/about/outcome-projects.png' ); ?>" alt="Дитина створюватиме реальні проєкти для перших професійних досягнень"></li></ul></div></section>
	<section class="about-history" aria-labelledby="about-history-title"><div class="container"><div class="about-history__layout"><div class="about-history__content"><h2 id="about-history-title">Logika – успішний освітній<br>проєкт з 2018 року</h2><div class="about-history__copy"><p>Наша школа є успішним освітнім проєктом, який діє з 2018 року та має понад 50 000 випускників. Навчаємо дітей 7–17 років, заняття проводимо онлайн та офлайн. Маємо два напрямки: програмування та англійська мова.</p><p>Крім основного навчання проводимо сезонні інтелектуальні квести з призами, їздимо в IT-табори до Карпат та заохочуємо до навчання різноманітними способами.</p><strong>Наша основна мета – навчити цікаво, легко та ефективно!</strong></div><a class="about-history__cta" href="#about-lead-form">Безкоштовний пробний урок&nbsp; →</a></div><div class="about-history__image"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/about/anniversary-full.png' ); ?>" alt="Logika святкує чотири роки"><span class="about-history__skill about-history__skill--team">командна робота</span><span class="about-history__skill about-history__skill--communication">комунікація</span><span class="about-history__skill about-history__skill--thinking">критичне мислення</span><span class="about-history__skill about-history__skill--creativity">креативність</span></div></div></div></section>
</main>
